# Permalinks
permalink:        pretty

# Setup
title:            Paul Groth
tagline:          
url:              https://pgroth.github.io
paginate:         1
baseurl:          https://pgroth.com/
author:
  name:           Paul Groth
  url:            http://pgroth.com
  email:          pgroth@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/pgroth/pgroth
